# Copyright (c) 2026 ProtoCentral Electronics
# SPDX-License-Identifier: MIT

"""``.HP6`` container -- decode, verify, export, repair.

The same DBLK frame is used by the live CDC0 stream and the recorded SD file;
only the container differs. See docs/HP6_DATA_FORMAT.md.
"""

from .format import (
    DBLK_MAGIC,
    DBLK_OVERHEAD,
    ECG_RATE_HZ,
    EEG_RATE_HZ,
    HDR_CHANNEL_SLOTS,
    INF_ECG_SUSPECT,
    INF_LOW_CONF,
    INF_STUB,
    INFER_CLASSES,
    InferSample,
    FILE_HDR_LEN,
    FILE_MAGIC,
    FILE_VERSION,
    PPG_RATE_HZ,
    SYNC_MAGIC,
    LEAD_OFF_LA,
    LEAD_OFF_LL,
    LEAD_OFF_RA,
    LEAD_OFF_V1,
    VIT_ECG_LEAD_OFF,
    VIT_HR_FROM_PPG,
    VIT_PPG_WEAK,
    Channel,
    EcgSample,
    EegSample,
    EventSample,
    EventType,
    FileHeader,
    Hp6Error,
    PpgSample,
    Sample,
    SyncSample,
    VitalsSample,
    lead_off_names,
    payload_for,
)
from .export import ExportResult, export_csv
from .idx import Idx, IdxEntry, idx_path_for, read_idx
from .reader import (
    Block,
    ReadStats,
    VerifyReport,
    iter_blocks,
    read_file,
    read_stream,
    verify,
)
from .repair import RepairResult, repair
from .writer import FileWriter, encode_block, new_header, wrap_capture

__all__ = [
    "Block",
    "Channel",
    "DBLK_MAGIC",
    "DBLK_OVERHEAD",
    "ECG_RATE_HZ",
    "EEG_RATE_HZ",
    "HDR_CHANNEL_SLOTS",
    "INF_ECG_SUSPECT",
    "INF_LOW_CONF",
    "INF_STUB",
    "INFER_CLASSES",
    "InferSample",
    "EcgSample",
    "EegSample",
    "EventSample",
    "EventType",
    "ExportResult",
    "FILE_HDR_LEN",
    "FILE_MAGIC",
    "FILE_VERSION",
    "FileHeader",
    "FileWriter",
    "Hp6Error",
    "Idx",
    "LEAD_OFF_LA",
    "LEAD_OFF_LL",
    "LEAD_OFF_RA",
    "LEAD_OFF_V1",
    "IdxEntry",
    "PPG_RATE_HZ",
    "PpgSample",
    "ReadStats",
    "RepairResult",
    "SYNC_MAGIC",
    "Sample",
    "SyncSample",
    "VerifyReport",
    "VIT_ECG_LEAD_OFF",
    "VIT_HR_FROM_PPG",
    "VIT_PPG_WEAK",
    "VitalsSample",
    "encode_block",
    "lead_off_names",
    "export_csv",
    "idx_path_for",
    "iter_blocks",
    "new_header",
    "payload_for",
    "read_file",
    "read_idx",
    "read_stream",
    "repair",
    "verify",
    "wrap_capture",
]
