/*
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_DISPLAY_ILITEK_ILI9881C_H_
#define ZEPHYR_DRIVERS_DISPLAY_ILITEK_ILI9881C_H_

#define LCD_TIMINGS_NODE DT_CHILD(DT_NODELABEL(zephyr_lcdif), display_timings)

#define LCD_HTIMMING_SYNC        DT_PROP(LCD_TIMINGS_NODE, hsync_len)
#define LCD_HTIMMING_BACK_PORCH  DT_PROP(LCD_TIMINGS_NODE, hback_porch)
#define LCD_HTIMMING_FRONT_PORCH DT_PROP(LCD_TIMINGS_NODE, hfront_porch)
#define LCD_HACTIVE_LINE         DT_PROP(DT_NODELABEL(zephyr_lcdif), width)
#define LCD_HTIMMING_TOTAL_CYC                                                                     \
	LCD_HACTIVE_LINE + LCD_HTIMMING_BACK_PORCH + LCD_HTIMMING_FRONT_PORCH + LCD_HTIMMING_SYNC

#define LCD_VTIMMING_SYNC        DT_PROP(LCD_TIMINGS_NODE, vsync_len)
#define LCD_VTIMMING_BACK_PORCH  DT_PROP(LCD_TIMINGS_NODE, vback_porch)
#define LCD_VTIMMING_FRONT_PORCH DT_PROP(LCD_TIMINGS_NODE, vfront_porch)
#define LCD_VACTIVE_LINE         DT_PROP(DT_NODELABEL(zephyr_lcdif), height)
#define LCD_VTIMMING_TOTAL_CYC                                                                     \
	LCD_VACTIVE_LINE + LCD_VTIMMING_BACK_PORCH + LCD_VTIMMING_FRONT_PORCH + LCD_VTIMMING_SYNC

#define ILITEK_ILI9881C_HSYNC LCD_HTIMMING_SYNC
#define ILITEK_ILI9881C_HBP   LCD_HTIMMING_BACK_PORCH - LCD_HTIMMING_SYNC
#define ILITEK_ILI9881C_HFP                                                                        \
	LCD_HTIMMING_TOTAL_CYC - LCD_HACTIVE_LINE - LCD_HTIMMING_BACK_PORCH - LCD_HTIMMING_SYNC

#define ILITEK_ILI9881C_VSYNC LCD_VTIMMING_SYNC
#define ILITEK_ILI9881C_VBP   LCD_VTIMMING_BACK_PORCH - LCD_VTIMMING_SYNC
#define ILITEK_ILI9881C_VFP                                                                        \
	LCD_VTIMMING_TOTAL_CYC - LCD_VACTIVE_LINE - LCD_VTIMMING_BACK_PORCH - LCD_VTIMMING_SYNC

#endif /* ZEPHYR_DRIVERS_DISPLAY_ILITEK_ILI9881C_H_ */
