#!/usr/bin/env python3
# Copyright (c) 2024-2026 Protocentral Electronics
# SPDX-License-Identifier: MIT
#
# Regenerate hpi_logo.c from the brand artwork in art/.
#
#     ~/zephyrproject/.venv/bin/python convert_logo.py      # needs Pillow
#
# The HealthyPi 6 lockup is exactly two colours over an alpha channel: the
# "HealthyPi" wordmark in on-surface white and the 6/hexagon/ECG trace in the
# brand amber. That is why this emits two LV_COLOR_FORMAT_A8 masks rather than
# one RGB565A8 image -- A8 is 1 byte per pixel instead of 3, and LVGL paints the
# brand colour with image_recolor, so the palette lives in the theme header
# (HPI_M3_ON_SURFACE / HPI_M3_SIG_ECG) instead of being baked into flash.
#
# Both masks are emitted at the full canvas size, deliberately. Cropping each to
# its own bounding box would save ~23 KB, but the two layers would then scale
# about different origins and the "6" could drift a pixel away from the wordmark
# at the non-native sizes. Registration is worth more than the flash.
#
# One master is emitted, at the largest size the UI asks for (the boot splash).
# The self-test and OTA screens scale it down at runtime; 312->158 under LVGL's
# bilinear transform was compared against a Lanczos reference and the thin ECG
# trace survives it.

import pathlib
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: ~/zephyrproject/.venv/bin/python -m pip install pillow")

import numpy as np

HERE = pathlib.Path(__file__).parent
SRC = HERE / "art" / "hpi6-dark.png"
OUT = HERE / "hpi_logo.c"

# Must match hpi_m3_theme.h. Only used to classify source pixels into the two
# layers -- the actual colour is applied at draw time by image_recolor.
ACCENT = (0xFB, 0xBF, 0x24)   # HPI_M3_SIG_ECG (Signal Amber)
LIGHT = (0xEC, 0xEF, 0xF1)    # HPI_M3_ON_SURFACE

# Boot splash width in device pixels (design 2a). 480x800 panel, canvas is 1:1.
MASTER_W = 312


def split_layers(path):
    """Return (w, h, light_mask, accent_mask) as full-canvas A8 planes."""
    im = Image.open(path).convert("RGBA")
    a = np.asarray(im).astype(np.int32)
    rgb, alpha = a[..., :3], a[..., 3]

    d_accent = np.abs(rgb - np.array(ACCENT)).sum(-1)
    d_light = np.abs(rgb - np.array(LIGHT)).sum(-1)

    # Nearest-brand-colour wins. The wordmark and the mark never touch, so an
    # antialiased pixel only ever blends one of them with the background and
    # this classification never splits a single edge across both layers.
    accent = np.where(d_accent <= d_light, alpha, 0)
    light = np.where(d_accent > d_light, alpha, 0)
    return im, light, accent


def scale_mask(im, mask, w, h):
    """Resample one alpha plane to w x h with a high-quality filter."""
    return np.asarray(
        Image.fromarray(mask.astype(np.uint8), mode="L").resize((w, h), Image.LANCZOS)
    )


def emit(f, name, mask, w, h):
    data = mask.tobytes()
    f.write(f"\nstatic const uint8_t {name}_map[] = {{\n")
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        f.write(f"\t{row},\n")
    f.write("};\n\n")
    f.write(f"const lv_image_dsc_t {name} = {{\n")
    f.write("\t.header = {\n")
    f.write("\t\t.magic = LV_IMAGE_HEADER_MAGIC,\n")
    f.write("\t\t.cf = LV_COLOR_FORMAT_A8,\n")
    f.write("\t\t.flags = 0,\n")
    f.write(f"\t\t.w = {w},\n")
    f.write(f"\t\t.h = {h},\n")
    f.write(f"\t\t.stride = {w},\n")
    f.write("\t\t.reserved_2 = 0,\n")
    f.write("\t},\n")
    f.write(f"\t.data_size = sizeof({name}_map),\n")
    f.write(f"\t.data = {name}_map,\n")
    f.write("};\n")
    return len(data)


def main():
    im, light, accent = split_layers(SRC)
    w = MASTER_W
    h = round(im.height * MASTER_W / im.width)
    light = scale_mask(im, light, w, h)
    accent = scale_mask(im, accent, w, h)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("/*\n")
        f.write(" * Copyright (c) 2024-2026 Protocentral Electronics\n")
        f.write(" * SPDX-License-Identifier: MIT\n")
        f.write(" *\n")
        f.write(" * GENERATED by ui/assets/convert_logo.py from ui/assets/art/hpi6-dark.png.\n")
        f.write(" * Do not edit by hand -- re-run the script instead.\n")
        f.write(" *\n")
        f.write(" * The HealthyPi 6 lockup as two LV_COLOR_FORMAT_A8 alpha masks sharing one\n")
        f.write(f" * {w}x{h} canvas: the wordmark and the amber mark. Painted by\n")
        f.write(" * hpi_ui_logo_create(), which recolours each layer from the theme.\n")
        f.write(" */\n")
        f.write('#include "hpi_logo.h"\n')
        total = 0
        total += emit(f, "hpi_logo_lockup_light", light, w, h)
        total += emit(f, "hpi_logo_lockup_accent", accent, w, h)

    print(f"{OUT}: {w}x{h}, 2 x A8, {total} B ({total / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
